{"name": "test_add_to_cart", "status": "skipped", "statusDetails": {"message": "Skipped: Не удалось подключиться к android Appium серверу после 3 попыток: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'kz.halyk.onlinebank.stage' application. Consider checking the driver's troubleshooting documentation. Original error: Error executing adbExec. Original error: 'Command '/Users/a00059362/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n kz.halyk.onlinebank.stage/kz.halyk.onlinebank.ui_release4.screens.auth.AuthActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'kz.halyk.onlinebank.stage' application. Consider checking the driver's troubleshooting documentation. Original error: Error executing adbExec. Original error: 'Command '/Users/a00059362/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n kz.halyk.onlinebank.stage/kz.halyk.onlinebank.ui_release4.screens.auth.AuthActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)", "trace": "('/Users/a00059362/Desktop/Новая папка/onlineduken/tests/test_order.py', 8, \"Skipped: Не удалось подключиться к android Appium серверу после 3 попыток: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'kz.halyk.onlinebank.stage' application. Consider checking the driver's troubleshooting documentation. Original error: Error executing adbExec. Original error: 'Command '/Users/a00059362/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n kz.halyk.onlinebank.stage/kz.halyk.onlinebank.ui_release4.screens.auth.AuthActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability\\nStacktrace:\\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'kz.halyk.onlinebank.stage' application. Consider checking the driver's troubleshooting documentation. Original error: Error executing adbExec. Original error: 'Command '/Users/a00059362/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n kz.halyk.onlinebank.stage/kz.halyk.onlinebank.ui_release4.screens.auth.AuthActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability\\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)\\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)\")"}, "attachments": [{"name": "stdout", "source": "dbe892e9-bd01-4fa7-a26c-484ab4466aac-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "6f96a2b5-93bd-486f-b98f-70c11d3aa39b-attachment.txt", "type": "text/plain"}], "start": 1759745922525, "stop": 1759745922525, "uuid": "b45acc0b-827c-4955-a1d3-51638b35c987", "historyId": "cae176eae04f611559d8490fd415b078", "testCaseId": "cae176eae04f611559d8490fd415b078", "fullName": "tests.test_order#test_add_to_cart", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "host", "value": "MacBook-Pro-00059362.local"}, {"name": "thread", "value": "21146-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}], "titlePath": ["tests", "test_order.py"]}