{"uuid": "1067a919-b6f0-4c6a-a14b-04f762c96963", "children": ["ba7ce304-f3a8-4a85-8256-e3d3823c85cd"], "befores": [{"name": "driver", "status": "skipped", "statusDetails": {"message": "Skipped: Не удалось подключиться к android Appium серверу после 3 попыток: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'kz.halyk.onlinebank.stage' application. Consider checking the driver's troubleshooting documentation. Original error: Error executing adbExec. Original error: 'Command '/Users/a00059362/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n kz.halyk.onlinebank.stage/kz.halyk.onlinebank.ui_release4.screens.auth.AuthActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'kz.halyk.onlinebank.stage' application. Consider checking the driver's troubleshooting documentation. Original error: Error executing adbExec. Original error: 'Command '/Users/a00059362/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start -W -n kz.halyk.onlinebank.stage/kz.halyk.onlinebank.ui_release4.screens.auth.AuthActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)\n", "trace": "  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/conftest.py\", line 307, in driver\n    pytest.skip(f\"Не удалось подключиться к {platform} Appium серверу после {attempts} попыток: {e}\")\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/a00059362/Desktop/Новая папка/onlineduken/.venv/lib/python3.13/site-packages/_pytest/outcomes.py\", line 159, in skip\n    raise Skipped(msg=reason, allow_module_level=allow_module_level)\n"}, "start": 1759745183131, "stop": 1759745406466}], "start": 1759745183131, "stop": 1759745406534}